# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152E1X2bKqbNs-xbp8g3u2XTw8uf3oWPU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

df=pd.read_csv('arrhythmia.data', na_values='?')
df=df.dropna()
X=df.iloc[:,:279]
Y=df.iloc[:,279]
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=42)
k=3
neigh=KNeighborsClassifier(n_neighbors=k)
neigh.fit(x_train,y_train)
print("Accuracy:", neigh.score(x_test, y_test))
y_pred =neigh.predict(x_test)
mat=confusion_matrix(y_test,y_pred)
report=classification_report(y_test,y_pred)
print("Confusion Matrix:\n",mat)
print("\nClassification Report:\n",report)