# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152E1X2bKqbNs-xbp8g3u2XTw8uf3oWPU
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

df=pd.read_csv('arrhythmia.data',na_values='?')
df=df.dropna()
X=df.iloc[:,:279]
Y=df.iloc[:,279]
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.3)
# function for knn
def knn(x_train,x_test,y_train,y_test):
  neigh=KNeighborsClassifier(n_neighbors=3)
  neigh.fit(x_train,y_train)
  y_pred=neigh.predict(x_test)
  return y_pred
# function for mean squared error
def mse(y_pred,y_test):
  ms_error=np.mean((y_pred-y_test)**2)
  return ms_error
# function for absolute mean error
def ma_error(y_pred,y_test):
  m_error=np.mean(np.abs(y_pred-y_test))
  return m_error
def mape(y_pred,y_tedt):
  map=np.mean(np.abs((y_pred-y_test)/y_pred*100))
  return map
def re(y_pred,y_test):
  r_error=1-np.var(y_pred)/np.var(y_test)
  return r_error
# body
y_pred=knn(x_train,x_test,y_train,y_test)
ms=mse(y_pred,y_test)
mae=ma_error(y_pred,y_test)
map=mape(y_pred,y_test)
r_error=re(y_pred,y_test)
print("mean squared error is:",ms)
print("mean absolute error is:",mae)
print("mean absolute percentage error is:",map)
print("R^2 error is:",r_error)