# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcY6a42cSHm8uD007vg6I82OAOPOSp5w
"""

import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
X=(np.random.rand(20))*9+1
Y=(np.random.rand(20))*9+1
print(X)
print(Y)
label=np.array([0 if((X[i]+Y[i])/2<=6) else 1 for i in range(20) ] )
x1=X[label==0]
y1=Y[label==0]
x2=X[label==1]
y2=Y[label==1]
plt.scatter(x1,y1,color='blue')
plt.scatter(x2,y2,color='red')
plt.show()