# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcY6a42cSHm8uD007vg6I82OAOPOSp5w
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
from sklearn.neighbors import KNeighborsClassifier
x=(np.random.rand(20))*9+1
y=(np.random.rand(20))*9+1
label=np.array([0 if (x[i]+y[i])/2<6 else 1 for i in range(20)])
X=np.arange(0,10,.1)
Y=np.arange(0,10,.1)
xx,yy=np.meshgrid(X,Y)
xx=xx.ravel()
yy=yy.ravel()
XY=np.c_[xx, yy]
xy=np.column_stack((x,y))
neigh=KNeighborsClassifier(n_neighbors=3)
neigh.fit(xy,label)
label_predict=neigh.predict(XY)
x1=xx[label_predict==0]
x2=xx[label_predict==1]
y1=yy[label_predict==0]
y2=yy[label_predict==1]
plt.scatter(x1,y1,color='blue')
plt.scatter(x2,y2,color='red')
plt.show()