# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcY6a42cSHm8uD007vg6I82OAOPOSp5w
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
from sklearn.neighbors import KNeighborsClassifier
df=pd.read_csv('arrhythmia.data',na_values='?')
df=df.dropna()
# function for various k
x=df.iloc[:,1]
y=df.iloc[:,2]
label=df.iloc[:,279]
print(x.min(),x.max(),y.min(),y.max())
def dif(k,x,y,label):
   X=np.arange(0,1,.1)
   Y=np.arange(119,182,.1)
   xx,yy=np.meshgrid(X,Y)
   xx=xx.ravel()
   yy=yy.ravel()
   XY=np.c_[xx, yy]
   xy=np.column_stack((x,y))
   neigh=KNeighborsClassifier(n_neighbors=k)
   neigh.fit(xy,label)
   label_predict=neigh.predict(XY)
   x1=xx[label_predict==0]
   x2=xx[label_predict==1]
   y1=yy[label_predict==0]
   y2=yy[label_predict==1]
   plt.scatter(x1,y1,color='blue')
   plt.scatter(x2,y2,color='red')
   plt.show()
for i in range(1,15):
  dif(i,x,y,label)