# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcY6a42cSHm8uD007vg6I82OAOPOSp5w
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid={'n_neighbors': np.arange(1, 15)}
knn=KNeighborsClassifier()
grid=GridSearchCV(knn, param_grid, cv=5)
x=(np.random.rand(20))*9+1
y=(np.random.rand(20))*9+1
xy=np.column_stack((x,y))
label=np.array([0 if (x[i]+y[i])/2<6 else 1 for i in range(20)])
grid.fit(xy, label)
best_k=grid.best_params_['n_neighbors']
print("Best k:", best_k)
print("Best cross-validation accuracy:", grid.best_score_)
X=np.arange(0,10,0.1)
Y=np.arange(0,10,0.1)
xx,yy=np.meshgrid(X,Y)
xx=xx.ravel()
yy=yy.ravel()
XY=np.c_[xx,yy]
final_knn=KNeighborsClassifier(n_neighbors=best_k)
final_knn.fit(xy, label)
label_predict=final_knn.predict(XY)
plt.scatter(xx[label_predict==0], yy[label_predict==0], color='blue', s=5)
plt.scatter(xx[label_predict==1], yy[label_predict==1], color='red', s=5)
plt.scatter(x[label==0], y[label==0], edgecolors='k', s=80)
plt.scatter(x[label==1], y[label==1], edgecolors='k', s=80)
plt.title("KNN Decision Regions (Best k = {})".format(best_k))
plt.xlabel("X")
plt.ylabel("Y")
plt.show()